{
  "swagger": "2.0",
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/subscriptions/{id}": {
      "put": {
        "tags": [
          "Subscription"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/SubscriptionResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Subscription ID"
          },
          {
            "schema": {
              "$ref": "#/definitions/SubscriptionUpdate"
            },
            "required": false,
            "name": "event",
            "in": "body",
            "description": "Subscription update attrs"
          }
        ],
        "operationId": "TdAuditWeb.SubscriptionController.update",
        "description": "Update Subscription"
      },
      "get": {
        "tags": [
          "Subscription"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "200": {
            "schema": {
              "$ref": "#/definitions/SubscriptionResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Subscription ID"
          }
        ],
        "operationId": "TdAuditWeb.SubscriptionController.show",
        "description": "Show a Subscription"
      }
    },
    "/subscriptions": {
      "post": {
        "tags": [
          "Subscription"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/SubscriptionResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/SubscriptionCreate"
            },
            "required": false,
            "name": "subscription",
            "in": "body",
            "description": "Subscription create attrs"
          }
        ],
        "operationId": "TdAuditWeb.SubscriptionController.create",
        "description": "Creates a Subscription"
      },
      "get": {
        "tags": [
          "Subscription"
        ],
        "summary": "",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/SubscriptionsResponse"
            },
            "description": "OK"
          }
        },
        "parameters": [],
        "operationId": "TdAuditWeb.SubscriptionController.index",
        "description": "List of subscriptions"
      }
    },
    "/subscription/{id}": {
      "delete": {
        "tags": [
          "Subscription"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "204": {
            "description": "No Content"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Subscription ID"
          }
        ],
        "operationId": "TdAuditWeb.SubscriptionController.delete",
        "description": "Delete Subscription"
      }
    },
    "/notifications_system/configurations/{id}": {
      "put": {
        "tags": [
          "Configuration"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/ConfigurationResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Configuration ID"
          },
          {
            "schema": {
              "$ref": "#/definitions/ConfigurationUpdate"
            },
            "required": false,
            "name": "event",
            "in": "body",
            "description": "Configuration update attrs"
          }
        ],
        "operationId": "TdAuditWeb.ConfigurationController.update",
        "description": "Update a Configuration from a given"
      },
      "get": {
        "tags": [
          "Configuration"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "200": {
            "schema": {
              "$ref": "#/definitions/ConfigurationResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Configuration ID"
          }
        ],
        "operationId": "TdAuditWeb.ConfigurationController.show",
        "description": "Show a Configuration from a give id"
      },
      "delete": {
        "tags": [
          "Configuration"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "204": {
            "description": "No Content"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Configuration ID"
          }
        ],
        "operationId": "TdAuditWeb.ConfigurationController.delete",
        "description": "Delete a Configuration from a given ID"
      }
    },
    "/notifications_system/configurations": {
      "post": {
        "tags": [
          "Configuration"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/ConfigurationResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/ConfigurationCreate"
            },
            "required": false,
            "name": "configuration",
            "in": "body",
            "description": "Configuration create attrs"
          }
        ],
        "operationId": "TdAuditWeb.ConfigurationController.create",
        "description": "Creates a Configuration for the notifications system"
      },
      "get": {
        "tags": [
          "Configuration"
        ],
        "summary": "",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/ConfigurationsResponse"
            },
            "description": "OK"
          }
        },
        "parameters": [],
        "operationId": "TdAuditWeb.ConfigurationController.index",
        "description": "List of configurations in our notification system"
      }
    },
    "/events/{id}": {
      "put": {
        "tags": [
          "Event"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/EventResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Event ID"
          },
          {
            "schema": {
              "$ref": "#/definitions/EventUpdate"
            },
            "required": false,
            "name": "event",
            "in": "body",
            "description": "Event update attrs"
          }
        ],
        "operationId": "TdAuditWeb.EventController.update",
        "description": "Update Event"
      },
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "200": {
            "schema": {
              "$ref": "#/definitions/EventResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Event ID"
          }
        ],
        "operationId": "TdAuditWeb.EventController.show",
        "description": "Show Event"
      },
      "delete": {
        "tags": [
          "Event"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "204": {
            "description": "No Content"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Event ID"
          }
        ],
        "operationId": "TdAuditWeb.EventController.delete",
        "description": "Delete Event"
      }
    },
    "/events": {
      "post": {
        "tags": [
          "Event"
        ],
        "summary": "",
        "responses": {
          "400": {
            "description": "Client Error"
          },
          "201": {
            "schema": {
              "$ref": "#/definitions/EventResponse"
            },
            "description": "OK"
          }
        },
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "schema": {
              "$ref": "#/definitions/EventCreate"
            },
            "required": false,
            "name": "event",
            "in": "body",
            "description": "Event create attrs"
          }
        ],
        "operationId": "TdAuditWeb.EventController.create",
        "description": "Creates Event"
      },
      "get": {
        "tags": [
          "Event"
        ],
        "summary": "",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/EventsResponse"
            },
            "description": "OK"
          }
        },
        "parameters": [],
        "operationId": "TdAuditWeb.EventController.index",
        "description": "List Events"
      }
    }
  },
  "info": {
    "version": "1.0",
    "title": "TdAudit"
  },
  "host": "localhost:4007",
  "definitions": {
    "SubscriptionsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Subscriptions"
        }
      }
    },
    "Subscriptions": {
      "type": "array",
      "title": "Subscriptions",
      "items": {
        "$ref": "#/definitions/Subscription"
      },
      "description": "A collection of subscriptions"
    },
    "SubscriptionUpdate": {
      "type": "object",
      "properties": {
        "subscription": {
          "type": "object",
          "required": [
            "user_email",
            "resource_type",
            "resource_id",
            "event"
          ],
          "properties": {
            "user_email": {
              "type": "string",
              "description": "Email of the subscriptor"
            },
            "resource_type": {
              "type": "string",
              "description": "Type of the resource triggering the event"
            },
            "resource_id": {
              "type": "integer",
              "description": "ID of the resource triggering the event"
            },
            "periodicity": {
              "type": "string",
              "description": "Periodicity of the subscription"
            },
            "event": {
              "type": "string",
              "description": "Event to subscribe"
            }
          }
        }
      }
    },
    "SubscriptionResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Subscription"
        }
      }
    },
    "SubscriptionCreate": {
      "type": "object",
      "properties": {
        "subscription": {
          "type": "object",
          "required": [
            "user_email",
            "resource_type",
            "resource_id",
            "event",
            "id"
          ],
          "properties": {
            "user_email": {
              "type": "string",
              "description": "Email of the subscriptor"
            },
            "resource_type": {
              "type": "string",
              "description": "Type of the resource triggering the event"
            },
            "resource_id": {
              "type": "integer",
              "description": "ID of the resource triggering the event"
            },
            "periodicity": {
              "type": "string",
              "description": "Periodicity of the subscription"
            },
            "id": {
              "type": "integer",
              "description": "Unique identifier"
            },
            "event": {
              "type": "string",
              "description": "Event to subscribe"
            }
          }
        }
      }
    },
    "Subscription": {
      "type": "object",
      "title": "Subscription",
      "properties": {
        "user_email": {
          "type": "string",
          "description": "Email of the subscriptor"
        },
        "resource_type": {
          "type": "string",
          "description": "Type of the resource triggering the event"
        },
        "resource_id": {
          "type": "integer",
          "description": "ID of the resource triggering the event"
        },
        "periodicity": {
          "type": "string",
          "description": "Periodicity of the subscription"
        },
        "last_consumed_event": {
          "type": "string",
          "description": "Timestamps"
        },
        "id": {
          "type": "integer",
          "description": "Unique identifier"
        },
        "event": {
          "type": "string",
          "description": "Event to subscribe"
        }
      },
      "description": "A subscription of an user to a notification"
    },
    "EventsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Events"
        }
      }
    },
    "Events": {
      "type": "array",
      "title": "Events",
      "items": {
        "$ref": "#/definitions/Event"
      },
      "description": "A collection of Events"
    },
    "EventUpdate": {
      "type": "object",
      "properties": {
        "event": {
          "type": "object",
          "required": [
            "user_name",
            "user_id",
            "service",
            "resource_type",
            "resource_id",
            "payload",
            "event"
          ],
          "properties": {
            "user_name": {
              "type": "string",
              "description": "User name"
            },
            "user_id": {
              "type": "integer",
              "description": "User ID"
            },
            "ts": {
              "type": "string",
              "description": "Timestamps"
            },
            "service": {
              "type": "string",
              "description": "Service audited"
            },
            "resource_type": {
              "type": "string",
              "description": "Resource type"
            },
            "resource_id": {
              "type": "integer",
              "description": "Resource ID"
            },
            "payload": {
              "type": "object",
              "description": "Payload"
            },
            "event": {
              "type": "string",
              "description": "Event name"
            }
          }
        }
      }
    },
    "EventResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Event"
        }
      }
    },
    "EventCreate": {
      "type": "object",
      "properties": {
        "event": {
          "type": "object",
          "required": [
            "user_name",
            "user_id",
            "service",
            "resource_type",
            "resource_id",
            "payload",
            "event"
          ],
          "properties": {
            "user_name": {
              "type": "string",
              "description": "User name"
            },
            "user_id": {
              "type": "integer",
              "description": "User ID"
            },
            "service": {
              "type": "string",
              "description": "Service audited"
            },
            "resource_type": {
              "type": "string",
              "description": "Resource type"
            },
            "resource_id": {
              "type": "integer",
              "description": "Resource ID"
            },
            "payload": {
              "type": "object",
              "description": "Payload"
            },
            "event": {
              "type": "string",
              "description": "Event name"
            }
          }
        }
      }
    },
    "Event": {
      "type": "object",
      "title": "Event",
      "required": [
        "user_name",
        "user_id",
        "ts",
        "service",
        "resource_type",
        "resource_id",
        "payload",
        "event",
        "id"
      ],
      "properties": {
        "user_name": {
          "type": "string",
          "description": "User name"
        },
        "user_id": {
          "type": "integer",
          "description": "User ID"
        },
        "ts": {
          "type": "string",
          "description": "Timestamps"
        },
        "service": {
          "type": "string",
          "description": "Service audited"
        },
        "resource_type": {
          "type": "string",
          "description": "Resource type"
        },
        "resource_id": {
          "type": "integer",
          "description": "Resource ID"
        },
        "payload": {
          "type": "object",
          "description": "Payload"
        },
        "id": {
          "type": "integer",
          "description": "Unique identifier"
        },
        "event": {
          "type": "string",
          "description": "Event name"
        }
      },
      "example": {
        "user_name": "some user name",
        "user_id": 1,
        "ts": "2018-05-08T17:17:59.691460",
        "service": "some service",
        "resource_type": "some resource type",
        "resource_id": 100,
        "payload": {
          "example": "payload"
        },
        "id": 12,
        "event": "some event"
      },
      "description": "An Event"
    },
    "ConfigurationsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Configurations"
        }
      }
    },
    "Configurations": {
      "type": "array",
      "title": "Configurations",
      "items": {
        "$ref": "#/definitions/Configuration"
      },
      "description": "A collection of configurations"
    },
    "ConfigurationUpdate": {
      "type": "object",
      "properties": {
        "configuration": {
          "type": "object",
          "required": [
            "settings",
            "event"
          ],
          "properties": {
            "settings": {
              "type": "object",
              "description": "Specifics of the configuration"
            },
            "event": {
              "type": "string",
              "description": "Event to create a configuration"
            }
          }
        }
      },
      "example": {
        "configuration": {
          "settings": {
            "generate_subscription": {
              "roles": [
                "data_officer"
              ]
            }
          },
          "event": "create_concept_draft"
        }
      }
    },
    "ConfigurationResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Configuration"
        }
      }
    },
    "ConfigurationCreate": {
      "type": "object",
      "properties": {
        "configuration": {
          "type": "object",
          "required": [
            "settings",
            "event"
          ],
          "properties": {
            "settings": {
              "type": "object",
              "description": "Specifics of the configuration"
            },
            "event": {
              "type": "string",
              "description": "Event to create a configuration"
            }
          }
        }
      },
      "example": {
        "configuration": {
          "settings": {
            "generate_subscription": {
              "roles": [
                "data_owner"
              ]
            },
            "generate_notification": {
              "active": false
            }
          },
          "event": "create_concept_draft"
        }
      }
    },
    "Configuration": {
      "type": "object",
      "title": "Configuration",
      "properties": {
        "settings": {
          "type": "object",
          "description": "Specifics of the configuration"
        },
        "id": {
          "type": "integer",
          "description": "Unique identifier"
        },
        "event": {
          "type": "string",
          "description": "Event to generate a configuration"
        }
      },
      "example": {
        "configuration": {
          "settings": {
            "generate_subscription": {
              "roles": [
                "data_owner"
              ]
            },
            "generate_notification": {
              "active": false
            }
          },
          "event": "create_concept_draft"
        }
      },
      "description": "A configuration for our notifications system"
    }
  },
  "basePath": "/api"
}